/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  BgStencilButton as BgStencilButton
} from './components/bg-stencil-button/bg-stencil-button';

declare global {
  interface HTMLBgStencilButtonElement extends BgStencilButton, HTMLStencilElement {
  }
  var HTMLBgStencilButtonElement: {
    prototype: HTMLBgStencilButtonElement;
    new (): HTMLBgStencilButtonElement;
  };
  interface HTMLElementTagNameMap {
    "bg-stencil-button": HTMLBgStencilButtonElement;
  }
  interface ElementTagNameMap {
    "bg-stencil-button": HTMLBgStencilButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "bg-stencil-button": JSXElements.BgStencilButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface BgStencilButtonAttributes extends HTMLAttributes {
      className?: string;
      text?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
